version: '3.8'

services:
  db:
    image: postgis/postgis:15-3.3
    container_name: verbclub-db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build:
      context: ./apps/api
      dockerfile: Dockerfile
    container_name: verbclub-api
    environment:
      - PORT=${PORT}
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_NAME=${DB_NAME}
      - JWT_SECRET=${JWT_SECRET}
    ports:
      - "3000:3000"
    volumes:
      - ./apps/api:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - db

  frontend:
    build:
      context: ./apps/web
      dockerfile: Dockerfile
    container_name: verbclub-frontend
    ports:
      - "8080:8080"
    volumes:
      - ./apps/web:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - api

  import:
    build:
      context: ./scripts
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_NAME=${DB_NAME}
    depends_on:
      - db
    profiles:
      - import

volumes:
  postgres_data: 