version: '3.8'

services:
  db:
    image: postgis/postgis:latest
    container_name: verbclub-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - verbclub-db:/var/lib/postgresql/data

  api:
    build: 
      context: ./apps/api
      dockerfile: Dockerfile
    container_name: verbclub-api
    environment:
      - PORT=${PORT}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_NAME=${DB_NAME}
      - JWT_SECRET=${JWT_SECRET}
    ports:
      - "3000:3000"
    volumes:
      - ./apps/api:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - db

  frontend:
    build:
      context: ./apps/web
      dockerfile: Dockerfile
    container_name: verbclub-frontend
    ports:
      - "8080:8080"
    volumes:
      - ./apps/web:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - api

volumes:
  verbclub-db: 